AllCops:
  TargetRubyVersion: 2.6.4

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/distribution/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Naming/FileName:
  Exclude:
    - 'Gemfile'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
